-- phpMyAdmin SQL Dump
-- version 4.8.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: 15-Ago-2019 às 06:46
-- Versão do servidor: 5.7.24
-- versão do PHP: 7.2.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `tcc`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `plantacao`
--

DROP TABLE IF EXISTS `plantacao`;
CREATE TABLE IF NOT EXISTS `plantacao` (
  `id_plantacao` int(11) NOT NULL AUTO_INCREMENT,
  `reino` varchar(10) NOT NULL,
  `divisao` varchar(15) NOT NULL,
  `classe` varchar(15) NOT NULL,
  `ordem` varchar(15) NOT NULL,
  `familia` varchar(20) NOT NULL,
  `genero` varchar(20) NOT NULL,
  `nome` varchar(30) NOT NULL,
  `temperatura` varchar(30) NOT NULL,
  `agua` varchar(100) NOT NULL,
  `solo` varchar(250) NOT NULL,
  `descricao` varchar(5000) NOT NULL,
  `foto` varchar(30) NOT NULL,
  PRIMARY KEY (`id_plantacao`)
) ENGINE=MyISAM AUTO_INCREMENT=12 DEFAULT CHARSET=latin1;

--
-- Extraindo dados da tabela `plantacao`
--

INSERT INTO `plantacao` (`id_plantacao`, `reino`, `divisao`, `classe`, `ordem`, `familia`, `genero`, `nome`, `temperatura`, `agua`, `solo`, `descricao`, `foto`) VALUES
(1, 'Plantae', 'Magnoliophyta', 'Liliopsida', 'Poales', 'Poaceae', 'Saccharum', 'Cana-de-açúcar', '22 a 30°C.', '1.200 a 1.300 mm.', 'O pH ideal do solo é em torno de 6,5 o que maximiza a disponibilidade de nutrientes. No entanto, as plantas podem tolerar um grau considerável de acidez ou alcalinidade do solo.', 'A cana-de-açúcar é conhecida por suas características peculiares: uma planta fina de formato cilíndrico, folhas grandes e pode alcançar até seis metros de altura. É com ela que se faz dois produtos essenciais para a economia mundial: o açúcar, parte indispensável da alimentação humana, e o álcool, utilizado nas bebidas alcoólicas como a cachaça, o vinho e a cerveja, ou como combustível para abastecer os carros, também conhecido como etanol. A altura que essa espécie atinge está diretamente ligada à quantidade de sol que ela recebe diariamente. Cultivados em locais de clima tropical ou sub-tropical, os pés de cana-de-açúcar são da mesma família de plantas como o milho, o arroz e a cevada. A cultura pode se desenvolver até em solos sem muitos recursos, como o cerrado. A cana produzida hoje é resultado de diversas melhorias genéticas feitas através do cruzamento de suas espécies. Praticamente toda cana-de-açúcar que o mundo produz vira álcool ou açúcar. Esse processo é relativamente simples, basta moer a cana para fazer escorrer o açúcar em estado líquido, o famoso caldo de cana. Se este caldo for fervido, o excesso de água evapora e ele se transforma em açúcar. Se ele for fermentado, vira álcool. Essa fermentação nada mais é, que o uso de microrganismos (leveduras) para quebrar as moléculas do caldo e ajudar na fabricação do álcool. As usinas que trabalham com a cana-de-açúcar aproveitam praticamente tudo da planta. Após retirar o caldo da cana, o que sobra é chamado de bagaço. Atualmente ele é utilizado pelas usinas para gerar energia elétrica e, em menor escala, biogás. Pesquisas promissoras mostram que este bagaço pode também virar álcool, o famoso etanol celulósico.', 'cana_de_acucar.jpg'),
(2, 'Plantae', 'Magnoliophyta', 'Liliopsida', 'Poales', 'Poaceae', 'Zea', 'Milho', '24 a 30°C.', '350 a 500 mm.', 'Solo rico em nitrogênio, bem adubado e com pH entre 5,5 a 6,5.', 'É um cereal bastante conhecido e cultivado em quase todo parte do brasil e como também no mundo. O milho é extensivamente utilizado como alimento humano como também para ração para alguns tipos de animais, devido às suas qualidades nutricionais. Atualmente o maior produtor mundial de milho é o Estados Unidos.\r\nA planta do milho pode chegar a uma altura de até 2,5 metros, embora haja variedades bem mais baixas. O caule tem aparência de bambu e as juntas estão geralmente a cinquenta centímetros de distância umas das outras. A fixação da raiz é relativamente fraca. A espiga é cilíndrica, e costuma nascer na metade da altura da planta.\r\nOs grãos são pequenos basicamente do tmanho da , e estão dispostos em fileiras regulares presas no sabugo, que formam a espiga. Eles têm dimensões, peso e textura variáveis, porem tudo interfere no seu tamanho como solo, plantio, terra entre outros. Cada espiga contém de duzentos a quatrocentos grãos. Dependendo da espécie, os grãos têm cores variadas, podendo ser amarelos, brancos, vermelhos, pretos, azuis ou marrons. O núcleo da semente tem um pericarpo que é utilizado como revestimento.', 'milho.jpg'),
(3, 'Plantae', 'Magnoliophyta', 'Magnoliopsida', 'Solanales', 'Solanaceae', 'Nicotiana', 'Tabaco', '20 a 30ºC.', 'Regue abundantemente o tabaco todas as noites por alguns dias até a planta estabelecer-se.', 'É uma planta muito resistente. Boa drenagem. O solo deve ter pH 5,8. Pouco crescimento e outros distúrbios podem ocorrer se o pH do solo for igual ou superior a 6,5.', 'Apesar de 20 mil famílias no Nordeste e 170 mil na região Sul estarem envolvidas com o plantio de fumo no Brasil, garantindo a exportação de 85% da produção brasileira, essa cultura é “altamente controlada por um reduzido número de indústrias fumageiras, algumas poucas produtoras de cigarros”, diz Amadeu Bonato à IHU On-Line.   De acordo com ele, o que “explica” a adesão desses agricultores familiares ao plantio de fumo é o “contrato de integração” com as empresas fumageiras, “que garante os insumos dentro da propriedade, assistência técnica, mercado garantido e sem que haja preocupação com o transporte do produto e, para uma parcela, garante boa renda”. Entretanto, ressalta, atualmente “a maioria” dos agricultores que cultiva fumo no país “consegue sobreviver”, mas “para um grupo de mais de 30% das famílias a renda líquida do fumo é inferior a dois salários mínimos mensais”.   Na entrevista a seguir, concedida por e-mail à IHU On-Line, Bonato defende a “diversificação” de culturas para a agricultura familiar e argumenta que, independentemente da relevância econômica, “o cultivo do fumo é um grande mito se observado a partir da ótica da agricultura familiar”, porque além de o fumo não ser um alimento, é “altamente tóxico” e gera “graves consequências para as pessoas envolvidas no processo produtivo”.   Amadeu Bonato é coordenador do Departamento de Estudos Socioeconômicos Rurais - Deser, onde é responsável pelas áreas das políticas sociais e desenvolve pesquisas, estudos e assessoria às organizações, movimentos, entidades e instituições vinculadas à agricultura familiar.', 'tabaco.jpg'),
(4, 'Plantae', 'Magnoliophyta', 'Magnoliopsida', 'Malvales', 'Malvaceae', 'Gossypium', 'Algodão', '20 a 30ºC.', '', 'Ideal que tenha um pH entre 6 e 7. Além de uma boa umidade.', 'Algodão são as fibras que são colhidas manualmente ou com a ajuda de máquinas. Sendo que a forma manual de coleta é feita normalmente nos arbórea e traz um produto muito mais livre de impurezas. De uma forma ou de outra, as fibras sempre contêm pequenas sementes negras e triangulares que precisam ser extraídas antes do processamento das fibras. As fibras são, de facto, pêlos originados da superfície das próprias sementes. Estas sementes ainda são aproveitadas na obtenção de um óleo comestível. Pesquisas indicam que o composto gossipol, extraído da semente, pode ser empregado como contraceptivo masculino. \r\nNos primeiros 28 dias após a abertura da flor, as referidas células crescem rapidamente em comprimento, até 91% do comprimento final. Em seguida, o crescimento dos 9% finais torna-se lento e estabiliza-se em torno dos 47-51 dias do florescimento. Aos 21 dias, a parede da célula se resume, basicamente, em cutícula e camada, fina, de celulose.\r\n', 'algodao.jpg'),
(5, 'Plantae', 'Magnoliophyta', 'Magnoliopsida', 'Fabales', '	Fabaceae', 'Glycine', 'Soja', '20 a 35ºC.', '', 'Solo fértil e com um nível de drenagem bom. ', 'A soja é uma planta herbácea, da classe Rosideae, ordem Fabales, família Fabaceae, subfamília  Papilionoideae, tribo Phaseoleae, gênero Glycine L., espécie max. As principais variedades comerciais apresentam caule híspido, pouco ramificado e raiz com eixo principal e muitas ramificações. Possuem folhas trifolioladas (exceto o primeiro par de folhas simples, no nó acima do nó cotiledonar). Têm flores de fecundação autógama, típicas da subfamília Papileonoideae, de cor branca, roxa ou intermediária. Desenvolvem vagens (legumes) levemente arqueadas que, à medida que amadurecem, evoluem da cor verde para amarelo-pálido, marrom-claro, marrom ou cinza, e que podem conter de uma a cinco sementes lisas, elípticas ou globosas, de tegumento amarelo pálido, com hilo preto, marrom ou amarelo-palha. Apresentam crescimento indeterminado (sem racemo terminal), determinado (com racemo terminal) ou semideterminado (intermediário).\r\nA estatura das plantas varia, dependendo das condições do ambiente e da variedade (cultivar). A estatura ideal está entre 60 a 110 cm, o que, em lavouras comerciais, pode facilitar a colheita mecânica e evitar o acamamento. O ambiente também influencia sua floração e, consequentemente, seu ciclo. A floração da soja responde ao nictoperíodo, ou duração da noite.', 'soja.jpg'),
(6, 'Plantae', 'Magnoliophyta', 'Magnoliopsida', 'Sapindales', '	Anacardiaceae', 'Anacardium', 'Caju', '18 a 35ºC.', 'Varia entre 800 e 1.500 mm que são divididos nos períodos de chuvas.', 'Solo profundo e com bastante umidade.', 'O Caju é umas das frutas mais populares do brasil, com o clima nosso clima isso nos favorece, pelo nosso clima ser bastante quente que nos contribui para um fruto ainda melhor. Com seu alto nível de nutrientes e proteínas como: minerais, cálcio, magnésio entres diversos, como também de forma medicinal.', 'caju.jpg'),
(7, 'Plantae', 'Anthophyta', 'Magnoliopsida', 'Sapindales', 'Anacardiaceae', 'Mangifera', 'Manga', '20 a 29°C.', '750 mm a 2.500 mm.', 'Bem drenado, úmido e com pH entre 5,5 a 7,5, pois são pouco tolerantes a alcalinidade.', 'A manga é uma das frutas mais procuradas no mundo. A procura tem aumentado bastante nos mercados interno e externo. Mas, para que se tenha êxito na sua cultura, é preciso adotar práticas de cultivo adequadas, de modo que o produto atenda às exigências do mercado consumidor. É essencial que a fruta tenha boa qualidade e o custo de sua produção seja competitivo. A manga varia consideravelmente em tamanho, forma, cor, presença de fibras, aroma, sabor, entre outros. O formato do fruto varia de arredondado a oval-oblongo ou alongado, com comprimento entre 6,25 e 25 cm em variedades diferentes. São encontradas nas cores amarelo, laranja e vermelha. Quando a fruta ainda não está madura, sua cor é verde. Sua polpa é extremamente suculenta, com uma gama de sabor muito doce. Em seu interior encontra-se uma única semente grande localizada no centro, que contém o embrião da planta. A manga amadurece em 100 a 150 dias após a floração. Fruta rica em uma variedade de fitoquímicos e nutrientes, a polpa da manga é rica em prebióticos, fibras alimentares, vitamina C, polifenóis, carotenóides e provitamina A. Além disto, a fruta tem muitas propriedades benéficas para saúde, tais como: ajuda a purificar o sangue, diurético, combate a bronquite, tem efeito expectorante e combate a acidez estomacal. No Nordeste, a manga é cultivada em todos os estados, em particular nas áreas irrigadas da região semiárida, que apresentam excelentes condições para o desenvolvimento da cultura e obtenção de elevada produtividade e qualidade de frutos. Em 2007 o Brasil representava o 7º lugar no ranking de maiores produtores de manga do mundo.', 'manga.jpg'),
(8, 'Plantae', 'Magnoliophyta', '	Magnoliopsida', 'Cucurbitales', 'Cucurbitaceae', 'Cucumis', 'Melão', '25 a 35°C graus e baixa umidad', 'A necessidade de água do plantio à colheita, varia de 3.000 m3/ha a 5.500 m3/ha.', 'pH entre 6,4 a 7,2.', 'Planta herbácea anual de comprimento variável até 10,0 m, caule rasteiro e volúvel provido de gavinhas. As folhas são grandes e recortadas, semelhantes às da melancia e pepinos. As flores são amareladas e surgem de 18 a 25 dias após o plantio, em sexos separados, primeiro as masculinas e depois de alguns dias ambas são produzidas, ocorrendo a polinização por conta dos insetos, principalmente abelhas. O fruto pode variar de globoso a oval, cascas de textura e cores diversas conforme o cultivar. A polpa contém muita água, é saborosa e nutritiva. O melão é uma fruta de formato oval com casca de cor amarela. A polpa do melão é verde clara e na parte oca encontram-se muitas sementes achatadas de cor clara. É uma fruta muito suculenta, pois é rica em água. O sabor do melão é levemente adocicado. O melão não é uma fruta calórica, pois 100 gramas dela contêm apenas 30 calorias. Rico em vitaminas A e C e do complexo B. É também uma excelente fonte de sais minerais como, por exemplo, ferro, cálcio e fósforo. É excelente para fazer sucos, sorvetes e refrescos. Os melões são cultivados em regiões de clima semiárido. No Brasil, há uma boa produção destes frutos na região nordestina. A região Nordeste é, atualmente, um dos grandes celeiros produtores de frutas do pais, destacando-se, no caso dos melões, os Estados do Rio Grande do Norte e do Ceará, com quase dois terços da produção total, e os Estados de Pernambuco e da Bahia, com quase um terço da produção. O melão e um fruto cultivado de uma planta rasteira. De maneira geral, o melão é composto por 80% de água e por uma quantidade moderada de açúcares. É uma das frutas mais ricas em sódio, mas também contém o potássio, magnésio e cálcio. A quantidade de betacaroteno varia. Quanto mais alaranjada a coloração da polpa, maior a concentração destes nutrientes.', 'melao.jpg'),
(9, 'Plantae', 'Magnoliophyta', 'Magnoliopsida', 'Malpighiales', 'Malpighiaceae', 'Malpighia', 'Acerola', '15 a 32ºC.', '1300 a 1700mm.', 'A planta desenvolve-se bem em solos nas faixas de pH 4.5 a 6.5. Profundos. Argiloarenosos com boa drenagem. Pois é sensível a solos encharcados.', 'A acerola é uma fruta nativa da América Central, América do Sul e das ilhas do Caribe, conhecida também como cereja das Antilhas. É muito conhecida por causa do seu grande teor de ácido ascórbico, ou seja, vitamina, com apenas dois frutos as necessidades diárias de vitamina C são sanadas. É importante ressaltar que quanto mais verde a fruta estiver mais vitamina C terá e ainda, dependendo da época da colheita essa pode sofrer alteração na quantidade de vitamina C. Além dessa, a acerola ainda contém vitamina A, B1, B2, B3, cálcio, fósforo e ferro. A acerola sofre variação em relação a sua cor, ao seu tamanho e ao seu formato, por possuir várias espécies. É extremamente frágil, permanece no pé por apenas dois dias após chegar à maturação. Quanto ao sabor, as acerolas podem ser doces, ácidas e superácidas sendo que sua utilização é maior na produção de sucos, o que não a restringe a outras finalidades. A fruta é bastante utilizada por pessoas com gripe, afecções pulmonares, doenças do fígado, doenças nasais e gengivais. Nasce de uma árvore chamada aceroleira que se desenvolve em regiões de clima tropical e subtropical. Sua proliferação pode ocorrer através do plantio da semente, por técnicas de enxerto e/ou por estaquia. A aceroleira possui porte médio de aproximadamente três metros de altura com características de arbusto. Sob irrigação constante, a árvore produz fruto o ano todo e em terrenos não regados com tanta frequência, produz fruto até quatro vezes por ano. Nesse caso, a aceroleira floresce e frutifica principalmente no período da primavera e do verão.', 'acerola.jpg'),
(10, 'Plantae', 'Magnoliophyta', 'Magnoliopsida', 'Malvales', 'Malvaceae', '	Theobroma', 'Cacau', '23 a 25°C.', '1.800 a 2.500mm.', 'pH entre 6,0 a 6,5.', 'No Brasil, o cacaueiro se deu bem no clima da Bahia, principal estado produtor da espécie. A árvore alcança 6 metros e tem flores brancas perfumadas, que lembram orquídeas e surgem em cachos direto do tronco. As sementes precisam de sol pleno e solo fértil para se desenvolver: prepare a cova com uma misture de terra, esterco (de vaca ou frango) e calcário dolomítico, um produto encontrado em casas agrícolas que deixa o solo menos ácido. Plante a semente a 1 cm de profundidade, para que ela tenha força de brotar, caso contrário, morre por fungos. Para a árvore se desenvolver rapidamente e, em três anos, produzir os primeiros frutos, adube-a com sulfato de amônio, superfosfato simples e cloreto de potássio a cada três meses, todos fertilizantes vendidos em grandes casas de jardinagem O cacau é uma espécie nativa da floresta tropical americana, pois ocorre em vários países, mas o centro de origem sugerido é a Amazônia. Está presente em vários países americanos, como Venezuela, Colômbia, Equador, Brasil e Guianas, países da América Central e México. Devido à importância do chocolate, termo originado do vocábulo maia xocolatl, passou a ser cultivado na Ásia e na África. É uma das frutas mais antigas domesticadas pelo homem, tendo sido muito utilizada pelos maias e astecas, sendo considerada sagrada e até valendo como moeda. O fruto do cacau é uma baga grande, com 15-25 cm de comprimento, com 20 a 50 sementes, envoltas por uma polpa adocicada e esbranquiçada, sendo a casca amarela ou roxa. Pelo rendimento médio, para obter-se 750 kg de cacau, usam-se 1.875 kg de sementes frescas, podendo-se obter vários produtos residuais, tais como mel, geleia, vinagre, polpa, néctar e outros. Apesar de as sementes serem a parte principal do fruto do cacau, há crescente interesse pela sua polpa. Segundo o tipo e a forma da semente, há diferentes tipos de cacau, chamados criolo, forasteiro e trinitário, além do comum, este mais amargo que o primeiro. Os frutos das variedades tipo criolo são grandes, com casca mais fina e rugosa, cor amarela ou alaranjada quando maduros, com sementes grandes, de cor branca a violeta pálida, com alto teor de polpa dando produto superior de qualidade. No Brasil, a CEPLAC (Comissão Executiva do Plano da Lavoura Cacaueira) é a instituição que mais estudou o cacaueiro e tem vários híbridos; recentemente, obteve variedades resistentes a doenças. Para a obtenção das sementes do cacau para a indústria de chocolate, há uma série de fases, desde a colheita até o final, passando pela quebra dos frutos, fermentação em cochos, secagem e armazenamento por até 90 dias.', 'cacau.jpg'),
(11, '	Plantae', 'Magnoliophyta', 'Liliopsida', 'Poales', 'Bromeliaceae', 'Ananas', 'Abacaxi', '22 a 32ºC.', '1,3 a 5,0 mm/dia, 60 a 150 mm/mês ou 1.000 a 1.500 mm/ano.', 'Bem drenado, arejado e com pH entre 4,5 a 5,5.', 'Investir na plantação de abacaxi é uma tarefa que pode trazer diversas vantagens para o produtor.  Primeiro pelo fato de que essa fruta é bem aceita no Brasil, sendo consumida na maioria dos lares, o que faz com este ramo seja bastante estável. Além disso, o país oferece um clima tropical que é perfeito para o cultivo do abacaxi.  Os abacaxis são consumidos in natura e também são processados e transformados em outros alimentos como, por exemplo, polpas, compostas, sucos, sorvetes, entre outras possibilidades.  Logo, a fruta oferece uma grande diversidade comercial, o que permite que o produtor possa negociar com empresas de setores diferentes e, consequentemente, aumente os seus lucros.  Outro ponto que vale ressaltar é a lucratividade do abacaxi, a qual é bem atraente, desde que, é claro, a plantação de abacaxi não seja comprometida por eventuais problemas, como é o caso de pestes, insetos e clima.   Porém, plantações de abacaxi com boa “colheita” trazem somas significativas de dinheiro para os empresários de sucesso, sendo que as taxas de juros cobradas para financiamento da plantação de abacaxi pérola, por exemplo, são reduzidas.', 'abacaxi.jpg');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
